sudo: required  # 권한 허용

language: java  # 언어
jdk:
  - openjdk11 # 버젼

services: docker

branches:
  only:
    - main  # main 브런치만 확인

cache: # 같은 의존성은 다음 배포 때부터 안 받는다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_script: # 스크립트 실행전
  - echo "Start Script"
  - echo "Start creating an image with dockerfile"
  - ./gradlew clean build # jar 생성

script:
  - ./gradlew test # 테스트 실행
  - docker build -t jukim1124/spring-test . # 이미지 생성

after_script:
  - echo "end Script"

before_deploy:
  - zip -r ci
  - mkdir -p deploy
  - mv ci.zip deploy/ci.zip

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-606492404586
  bucket_path: docker-react-app
  local_dir: deploy
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
