version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=studyDB
    ports:
      - 3306:3306
    container_name: mysql
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    container_name: sync_backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/studyDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    container_name: sync_frontend
    ports:
      - 3000:3000
